export { isFirebaseConfigured, firebaseAuth, firestore } from './client.ts'
export { observeAuth, signInToStronger, signOutOfStronger } from './auth.ts'
export { previewSheetMigration, importSheetMigration } from './migration.ts'
export type { MigrationPreview } from './migration.ts'
export {
	SCHEMA_VERSION,
	ensureUser,
	readConfigZone,
	writeDefaultConfig,
	writeConfigValues,
	readWorkoutDefs,
	writeWorkoutDefs,
	writeDefaultWorkoutDefs,
	readCardioActivities,
	writeCardioActivities,
	writeDefaultCardioActivities,
	appendLogRows,
	readLogZone,
	updateLogRows,
	deleteLogSession,
	readFlags,
	writeFlags,
	readWorkoutSchedule,
	writeWorkoutSchedule,
	readSchedule,
	writeSchedule,
	readSettings,
	writeSettings,
	readMealItems,
	writeMealItems,
	readMealFavorites,
	writeMealFavorites,
	readMealRecents,
	writeMealRecents,
	readMealLog,
	appendMealLogEntry,
	deleteMealLogEntry,
	updateMealLogEntry,
	updateMealLogEntryCategory,
	readGarminActivities,
	writeGarminActivities,
	writeStravaActivities,
	readGarminWellnessEntries,
	writeGarminWellnessEntries,
	readWithingsMeasurements,
	writeWithingsMeasurements,
	recordMigration,
	verifyScheduleTab,
	createScheduleTab,
	verifyWorkoutScheduleTab,
	createWorkoutScheduleTab,
	verifyMealFavoritesTab,
	createMealFavoritesTab,
	verifyMealRecentsTab,
	createMealRecentsTab,
	verifyGarminTab,
	verifyGarminWellnessTab,
	verifyWithingsTab,
	createWithingsTab,
	verifySettingsTab,
	createSettingsTab,
	withDataRetry,
	withAuthRetry,
} from './store.ts'
