export { isFirebaseConfigured, firebaseAuth, firestore } from './client.ts'
export { observeAuth, signInToStronger, signOutOfStronger } from './auth.ts'
export {
	SCHEMA_VERSION,
	type YearBucketReadScope,
	type DateWindow,
	mergeYearScopedEntries,
	mergeDateWindowEntries,
	ensureUser,
	readConfigZone,
	writeDefaultConfig,
	writeConfigValues,
	readWorkoutDefs,
	writeWorkoutDefs,
	writeDefaultWorkoutDefs,
	readCardioActivities,
	writeCardioActivities,
	writeDefaultCardioActivities,
	appendLogRows,
	mergeWorkoutSessionRows,
	readLogZone,
	updateLogRows,
	deleteLogSession,
	readFlags,
	writeFlags,
	writeFlagDates,
	readWorkoutSchedule,
	writeWorkoutSchedule,
	writeWorkoutScheduleDates,
	readSchedule,
	writeSchedule,
	readSettings,
	writeSettings,
	readGarminActivities,
	writeGarminActivities,
	readGarminWellnessEntries,
	writeGarminWellnessEntries,
	readWithingsMeasurements,
	writeWithingsMeasurements,
	verifyScheduleTab,
	createScheduleTab,
	verifyWorkoutScheduleTab,
	createWorkoutScheduleTab,
	verifyGarminTab,
	verifyGarminWellnessTab,
	verifyWithingsTab,
	createWithingsTab,
	verifySettingsTab,
	createSettingsTab,
	withDataRetry,
	withAuthRetry,
} from './store.ts'
