export { isFirebaseConfigured, firebaseAuth, firestore } from './client.ts'
export { observeAuth, signInToStronger, signOutOfStronger } from './auth.ts'
export {
	clearPendingMutations,
	clearOfflineUserState,
	hasPendingMutations,
	retryPendingWrites,
	setActiveSyncUser,
	subscribeToSyncStatus,
	trackMutation,
	type SyncSnapshot,
} from './offline.ts'
export {
	SCHEMA_VERSION,
	type FirestoreReadSource,
	type YearBucketReadScope,
	type DateWindow,
	type StoredCycleDraft,
	type CycleConfigUpdate,
	mergeYearScopedEntries,
	mergeDateWindowEntries,
	ensureUser,
	readConfigZone,
	writeDefaultConfig,
	writeConfigValues,
	readCycleProgress,
	readCycleDrafts,
	writeCycleStart,
	writeCycleDraftResults,
	finishCycleSession,
	readWorkoutDefs,
	writeWorkoutDefs,
	writeDefaultWorkoutDefs,
	readCardioActivities,
	writeCardioActivities,
	writeDefaultCardioActivities,
	appendLogRows,
	mergeWorkoutSessionRows,
	readLogZone,
	updateLogRows,
	deleteLogSession,
	readFlags,
	writeFlags,
	writeFlagDates,
	readWorkoutSchedule,
	writeWorkoutSchedule,
	writeWorkoutScheduleDates,
	readSettings,
	writeSettings,
	readGarminActivities,
	writeGarminActivities,
	readGarminWellnessEntries,
	writeGarminWellnessEntries,
	readWithingsMeasurements,
	writeWithingsMeasurements,
} from './store.ts'
